### ISSUE TITLE
Code license assignment

### ISSUE THREAD

**Issue by synecdoche** [danfuzz/samizdat#779]
For the record:

* I hereby license all code I contribute to this project, under the
  stated terms of this project's license.
* I hereby authorize the project's maintainers and their designated
  agents to act as my agent, for the purpose of copyright management
  of my contributions to this project.
* All code I contribute to this project is my own original work.
* I am not subject to any obligation that prevents me from contributing to
  this project under these terms.

Signed,
john spurling

**Comment by danfuzz** [comment]
Thanks! I look forward to your PRs.
