### ISSUE TITLE
Overflow error with generator range ending at 9_223_372_036_854_775_807

### ISSUE THREAD

**Issue by synecdoche** [danfuzz/samizdat#782]
SUMMARY
-------

The following Samizdat program fails with an error:

````
for (x in (0..9_223_372_036_854_775_807)) {
    note("\(x)")
};
````

STEPS TO REPRODUCE
-------------------

1. Put the code in the previous section in a file called `overflow.sam`
2. Run: `samex --runtime=tot overflow.sam`

EXPECTED RESULT
---------------

````
0
1
2
[...]
9223372036854775804
9223372036854775805
9223372036854775806
9223372036854775807
````

ACTUAL RESULT
-------------

````
Overflow / error onadd(9223372036854775807, 1).
    at Int.add on 9223372036854775807
    at meta_ClosedRange.newInclusive on @<user class ClosedRange>
    at anonymous instance of Closure
    at anonymous instance of Closure
    at anonymous instance of Closure
    at meta_If.maybeValue on If
    at runProgram (instance of Closure)
    at runTextFile (instance of Closure)
    at anonymous instance of Closure
    at meta_If.maybeValue on If
    at anonymous instance of Closure
    at meta_If.is on If
    at runFile (instance of Closure)
    at anonymous instance of Closure
    at meta_If.maybeValue on If
    at anonymous instance of Closure
    at meta_If.cases on If
    at anonymous instance of Closure
    at runCommandLine (instance of Closure)
````

CONTEXT
-------

* Version: branch `master` as of change `b9614f74cecd66a5cab3e2c57243d3a104654705`
* OS: Linux Mint 17
* Compiler: gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

ADDITIONAL INFORMATION
----------------------

Ints are meant to be BigInts, so 9_223_372_036_854_775_807 should be valid, no? Even with a limit of 64 bits signed, I would expect that 2<sup>63</sup> - 1 would still be valid.

**Comment by danfuzz** [comment]
> Ints are meant to be BigInts, so 9_223_372_036_854_775_807 should be valid, no? Even with a limit of 64 bits signed, I would expect that 263 - 1 would still be valid.

Yes, but… `ClosedRange`'s underlying implementation calculates the size of the range, which in this case is out of the range of a 64-bit signed int. Here's the code in question:

```
def size = limitInt.sub(firstInt).div(increment).add(1);
```

where `firstInt == 0` and `increment == 1` in this case.

The intent is that the "real" runtime will have bigints, in which case this code would work just fine. In the mean time, there are going to be a few edge cases such as this one.

I'm closing this as not-a-bug. It's a known limitation, and already documented as such in the language guide's appendix.

Nonetheless, thanks for continuing to explore Samizdat and filing this issue!

**Comment by danfuzz** [comment]
I should add:

>EXPECTED RESULT
>0
>1
>2
>[...]
>9223372036854775804
>9223372036854775805
>9223372036854775806
>9223372036854775807

If the runtime managed to do one iteration per nanosecond, this would still take about 292 years to complete.

**Comment by synecdoche** [comment]
Hey, I'm in it for the long haul.

**Comment by danfuzz** [comment]
:smile_cat: :truck:

**Comment by synecdoche** [comment]
Oh, and I should add that I don't quite get your explanation about the range given that the following program has the same problem:

````
for (x in (9_223_372_036_854_775_806..9_223_372_036_854_775_807)) {
    note("\(x)")
};
````

**Comment by danfuzz** [comment]
Not 100% sure, but I'll bet that's because when it's generating, it adds 1 at the end just before it *would have* detected that it hit the end of the range.
